title:            Neerav Kumar
tagline:          Balling Hard, one command at a time
description:      Balling Hard, one command at a time
canonical: http://nero.io

# Owner/author information
owner:
  name:           Neerav Kumar
  avatar:         avatar.png
  bio:            "Balling Hard, one command at a time"
  email:          me@nero.im
  twitter:        neeravkumar
  github:         neeravkumar
  disqus:         neeravkumar
  location:       "Singapore"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/neeravkumar
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Singapore
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
