# Site settings
title: Neerav Kumar
email: me@nero.im
author: Neerav Kumar
description: "A Devops Engineer, a fanatic worker for what he believes in and a fantastic no-shit-giver for things he doesn't believe in"
baseurl: ""
url: "http://nero.io"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true

